# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'Default'
 

jobs:
      # - job: Build
      #   displayName: Build Maven Project
      #   steps:
        
      #   - task: Maven@3
      #     displayName: Buildin From Main POM 
      #     inputs:
      #       mavenPomFile: '$(system.defaultWorkingDirectory)/MAINPOM/pom.xml'
      #       goals: 'clean package'
      #       publishJUnitResults: true
      #       testResultsFiles: '**/surefire-reports/TEST-*.xml'
      #       javaHomeOption: 'JDKVersion'
      #       mavenAuthenticateFeed: false
      #       effectivePomSkip: false
  
      #   - task: CopyFiles@2
      #     displayName: 'Copy Files to artifact staging directory'
      #     inputs:
      #       SourceFolder: '$(System.DefaultWorkingDirectory)'
      #       Contents: '**/target/*.?(ear)'
      #       TargetFolder: $(Build.ArtifactStagingDirectory)
 
      #   - task: PublishBuildArtifacts@1
      #     inputs:
      #       pathToPublish: $(Build.ArtifactStagingDirectory)
      #       artifactName: Maven Build Output
         

      #   - task: PublishTestResults@2
      #     inputs:
      #           testResultsFormat: 'JUnit'
      #           testResultsFiles: '**/TEST-*.xml'
      #           failTaskOnFailedTests: true
      #           testRunTitle: 'SOAPUITest'

      - job: Shell
        displayName: Run Shell Script
        # dependsOn: Build
        # condition: succeeded('Build')
        steps:
            - task: Bash@3
              inputs:
                    targetType: 'inline'
                    script: |
                      a=$($(system.defaultWorkingDirectory)/test.bash)
            #           echo $a
            # - task: ShellScript@2
            #   inputs:
            #     scriptPath: test.sh
            #     failOnStandardError: true

                